package com.dd.mdr.model;
// Generated Mar 11, 2016 5:28:44 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SourceDataSkill generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_DATA_SKILL", schema = "DDMDR")
public class SourceDataSkill implements java.io.Serializable {

	private BigDecimal sdskId;
	private String sdskSkillNumber;
	private String sdskDescr;
	private String sdskClientCode;
	private String sdskClientName;
	private String sdskSiteCode;
	private Date sdskCreateDate;
	private String sdskCreateBy;
	private Date sdskUpdateDate;
	private String sdskUpdateBy;

	public SourceDataSkill() {
	}

	public SourceDataSkill(BigDecimal sdskId) {
		this.sdskId = sdskId;
	}

	public SourceDataSkill(BigDecimal sdskId, String sdskSkillNumber, String sdskDescr, String sdskClientCode,
			String sdskClientName, String sdskSiteCode, Date sdskCreateDate, String sdskCreateBy, Date sdskUpdateDate,
			String sdskUpdateBy) {
		this.sdskId = sdskId;
		this.sdskSkillNumber = sdskSkillNumber;
		this.sdskDescr = sdskDescr;
		this.sdskClientCode = sdskClientCode;
		this.sdskClientName = sdskClientName;
		this.sdskSiteCode = sdskSiteCode;
		this.sdskCreateDate = sdskCreateDate;
		this.sdskCreateBy = sdskCreateBy;
		this.sdskUpdateDate = sdskUpdateDate;
		this.sdskUpdateBy = sdskUpdateBy;
	}

	@Id

	@Column(name = "SDSK_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSdskId() {
		return this.sdskId;
	}

	public void setSdskId(BigDecimal sdskId) {
		this.sdskId = sdskId;
	}

	@Column(name = "SDSK_SKILL_NUMBER", length = 20)
	public String getSdskSkillNumber() {
		return this.sdskSkillNumber;
	}

	public void setSdskSkillNumber(String sdskSkillNumber) {
		this.sdskSkillNumber = sdskSkillNumber;
	}

	@Column(name = "SDSK_DESCR", length = 500)
	public String getSdskDescr() {
		return this.sdskDescr;
	}

	public void setSdskDescr(String sdskDescr) {
		this.sdskDescr = sdskDescr;
	}

	@Column(name = "SDSK_CLIENT_CODE", length = 20)
	public String getSdskClientCode() {
		return this.sdskClientCode;
	}

	public void setSdskClientCode(String sdskClientCode) {
		this.sdskClientCode = sdskClientCode;
	}

	@Column(name = "SDSK_CLIENT_NAME", length = 500)
	public String getSdskClientName() {
		return this.sdskClientName;
	}

	public void setSdskClientName(String sdskClientName) {
		this.sdskClientName = sdskClientName;
	}

	@Column(name = "SDSK_SITE_CODE", length = 20)
	public String getSdskSiteCode() {
		return this.sdskSiteCode;
	}

	public void setSdskSiteCode(String sdskSiteCode) {
		this.sdskSiteCode = sdskSiteCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SDSK_CREATE_DATE", length = 7)
	public Date getSdskCreateDate() {
		return this.sdskCreateDate;
	}

	public void setSdskCreateDate(Date sdskCreateDate) {
		this.sdskCreateDate = sdskCreateDate;
	}

	@Column(name = "SDSK_CREATE_BY", length = 30)
	public String getSdskCreateBy() {
		return this.sdskCreateBy;
	}

	public void setSdskCreateBy(String sdskCreateBy) {
		this.sdskCreateBy = sdskCreateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SDSK_UPDATE_DATE", length = 7)
	public Date getSdskUpdateDate() {
		return this.sdskUpdateDate;
	}

	public void setSdskUpdateDate(Date sdskUpdateDate) {
		this.sdskUpdateDate = sdskUpdateDate;
	}

	@Column(name = "SDSK_UPDATE_BY", length = 30)
	public String getSdskUpdateBy() {
		return this.sdskUpdateBy;
	}

	public void setSdskUpdateBy(String sdskUpdateBy) {
		this.sdskUpdateBy = sdskUpdateBy;
	}

}
