package com.dd.mdr.model.f;
// Generated Mar 11, 2016 5:28:44 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CallAgent generated by hbm2java
 */
@Entity
@Table(name = "CALL_AGENT", schema = "DDMDR", uniqueConstraints = @UniqueConstraint(columnNames = "CAGNT_EXTERNAL_ID") )
public class CallAgent implements java.io.Serializable {

	private BigDecimal cagntId;
	private String cagntExternalId;
	private String cagntSwitchId;
	private String cagntFirstName;
	private String cagntLastName;
	private BigDecimal cagntCrmId;
	private Date cagntCreateDate;
	private String cagntCreateBy;
	private Date cagntUpdateDate;
	private String cagntUpdateBy;
	private Set calls = new HashSet(0);

	public CallAgent() {
	}

	public CallAgent(BigDecimal cagntId, String cagntExternalId, String cagntLastName) {
		this.cagntId = cagntId;
		this.cagntExternalId = cagntExternalId;
		this.cagntLastName = cagntLastName;
	}

	public CallAgent(BigDecimal cagntId, String cagntExternalId, String cagntSwitchId, String cagntFirstName,
			String cagntLastName, BigDecimal cagntCrmId, Date cagntCreateDate, String cagntCreateBy,
			Date cagntUpdateDate, String cagntUpdateBy, Set calls) {
		this.cagntId = cagntId;
		this.cagntExternalId = cagntExternalId;
		this.cagntSwitchId = cagntSwitchId;
		this.cagntFirstName = cagntFirstName;
		this.cagntLastName = cagntLastName;
		this.cagntCrmId = cagntCrmId;
		this.cagntCreateDate = cagntCreateDate;
		this.cagntCreateBy = cagntCreateBy;
		this.cagntUpdateDate = cagntUpdateDate;
		this.cagntUpdateBy = cagntUpdateBy;
		this.calls = calls;
	}

	@Id

	@Column(name = "CAGNT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCagntId() {
		return this.cagntId;
	}

	public void setCagntId(BigDecimal cagntId) {
		this.cagntId = cagntId;
	}

	@Column(name = "CAGNT_EXTERNAL_ID", unique = true, nullable = false, length = 20)
	public String getCagntExternalId() {
		return this.cagntExternalId;
	}

	public void setCagntExternalId(String cagntExternalId) {
		this.cagntExternalId = cagntExternalId;
	}

	@Column(name = "CAGNT_SWITCH_ID", length = 100)
	public String getCagntSwitchId() {
		return this.cagntSwitchId;
	}

	public void setCagntSwitchId(String cagntSwitchId) {
		this.cagntSwitchId = cagntSwitchId;
	}

	@Column(name = "CAGNT_FIRST_NAME", length = 100)
	public String getCagntFirstName() {
		return this.cagntFirstName;
	}

	public void setCagntFirstName(String cagntFirstName) {
		this.cagntFirstName = cagntFirstName;
	}

	@Column(name = "CAGNT_LAST_NAME", nullable = false, length = 100)
	public String getCagntLastName() {
		return this.cagntLastName;
	}

	public void setCagntLastName(String cagntLastName) {
		this.cagntLastName = cagntLastName;
	}

	@Column(name = "CAGNT_CRM_ID", precision = 22, scale = 0)
	public BigDecimal getCagntCrmId() {
		return this.cagntCrmId;
	}

	public void setCagntCrmId(BigDecimal cagntCrmId) {
		this.cagntCrmId = cagntCrmId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAGNT_CREATE_DATE", length = 7)
	public Date getCagntCreateDate() {
		return this.cagntCreateDate;
	}

	public void setCagntCreateDate(Date cagntCreateDate) {
		this.cagntCreateDate = cagntCreateDate;
	}

	@Column(name = "CAGNT_CREATE_BY", length = 30)
	public String getCagntCreateBy() {
		return this.cagntCreateBy;
	}

	public void setCagntCreateBy(String cagntCreateBy) {
		this.cagntCreateBy = cagntCreateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAGNT_UPDATE_DATE", length = 7)
	public Date getCagntUpdateDate() {
		return this.cagntUpdateDate;
	}

	public void setCagntUpdateDate(Date cagntUpdateDate) {
		this.cagntUpdateDate = cagntUpdateDate;
	}

	@Column(name = "CAGNT_UPDATE_BY", length = 30)
	public String getCagntUpdateBy() {
		return this.cagntUpdateBy;
	}

	public void setCagntUpdateBy(String cagntUpdateBy) {
		this.cagntUpdateBy = cagntUpdateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "callAgent")
	public Set getCalls() {
		return this.calls;
	}

	public void setCalls(Set calls) {
		this.calls = calls;
	}

}
