package com.dd.mdr.model.f;
// Generated Mar 11, 2016 5:28:44 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Call generated by hbm2java
 */
@Entity
@Table(name = "CALL", schema = "DDMDR")
public class Call implements java.io.Serializable {

	private BigDecimal callId;
	private SourceLog sourceLog;
	private Communication communication;
	private CallAgent callAgent;
	private Location location;
	private BigDecimal ccId;
	private BigDecimal ciId;
	private BigDecimal cwkgpId;
	private BigDecimal tzoneId;
	private BigDecimal csltId;
	private String callExternalId;
	private Date callInitiatedDate;
	private Date callConnectedDate;
	private Date callAgentAnswerDate;
	private Date callEndDate;
	private Date callWorkgroupQueueDate;
	private Date callDispositionDate;
	private String callPhoneNumber;
	private Character callPhoneType;
	private BigDecimal callDuration;
	private char callDirection;
	private BigDecimal callTypeCmetaId;
	private BigDecimal callDialerModeCmetaId;
	private char callAbandonedFlag;
	private BigDecimal callAttempts;
	private BigDecimal callCrmId;
	private Date callCreateDate;
	private String callCreateBy;
	private Date callUpdateDate;
	private String callUpdateBy;
	private String callSecondaryExtId;
	private Set callEvents = new HashSet(0);

	public Call() {
	}

	public Call(BigDecimal callId, Communication communication, CallAgent callAgent, Location location,
			String callExternalId, char callDirection, char callAbandonedFlag) {
		this.callId = callId;
		this.communication = communication;
		this.callAgent = callAgent;
		this.location = location;
		this.callExternalId = callExternalId;
		this.callDirection = callDirection;
		this.callAbandonedFlag = callAbandonedFlag;
	}

	public Call(BigDecimal callId, SourceLog sourceLog, Communication communication, CallAgent callAgent,
			Location location, BigDecimal ccId, BigDecimal ciId, BigDecimal cwkgpId, BigDecimal tzoneId,
			BigDecimal csltId, String callExternalId, Date callInitiatedDate, Date callConnectedDate,
			Date callAgentAnswerDate, Date callEndDate, Date callWorkgroupQueueDate, Date callDispositionDate,
			String callPhoneNumber, Character callPhoneType, BigDecimal callDuration, char callDirection,
			BigDecimal callTypeCmetaId, BigDecimal callDialerModeCmetaId, char callAbandonedFlag,
			BigDecimal callAttempts, BigDecimal callCrmId, Date callCreateDate, String callCreateBy,
			Date callUpdateDate, String callUpdateBy, String callSecondaryExtId, Set callEvents) {
		this.callId = callId;
		this.sourceLog = sourceLog;
		this.communication = communication;
		this.callAgent = callAgent;
		this.location = location;
		this.ccId = ccId;
		this.ciId = ciId;
		this.cwkgpId = cwkgpId;
		this.tzoneId = tzoneId;
		this.csltId = csltId;
		this.callExternalId = callExternalId;
		this.callInitiatedDate = callInitiatedDate;
		this.callConnectedDate = callConnectedDate;
		this.callAgentAnswerDate = callAgentAnswerDate;
		this.callEndDate = callEndDate;
		this.callWorkgroupQueueDate = callWorkgroupQueueDate;
		this.callDispositionDate = callDispositionDate;
		this.callPhoneNumber = callPhoneNumber;
		this.callPhoneType = callPhoneType;
		this.callDuration = callDuration;
		this.callDirection = callDirection;
		this.callTypeCmetaId = callTypeCmetaId;
		this.callDialerModeCmetaId = callDialerModeCmetaId;
		this.callAbandonedFlag = callAbandonedFlag;
		this.callAttempts = callAttempts;
		this.callCrmId = callCrmId;
		this.callCreateDate = callCreateDate;
		this.callCreateBy = callCreateBy;
		this.callUpdateDate = callUpdateDate;
		this.callUpdateBy = callUpdateBy;
		this.callSecondaryExtId = callSecondaryExtId;
		this.callEvents = callEvents;
	}

	@Id

	@Column(name = "CALL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCallId() {
		return this.callId;
	}

	public void setCallId(BigDecimal callId) {
		this.callId = callId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SL_ID")
	public SourceLog getSourceLog() {
		return this.sourceLog;
	}

	public void setSourceLog(SourceLog sourceLog) {
		this.sourceLog = sourceLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMM_ID", nullable = false)
	public Communication getCommunication() {
		return this.communication;
	}

	public void setCommunication(Communication communication) {
		this.communication = communication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAGNT_ID", nullable = false)
	public CallAgent getCallAgent() {
		return this.callAgent;
	}

	public void setCallAgent(CallAgent callAgent) {
		this.callAgent = callAgent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID", nullable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@Column(name = "CC_ID", precision = 22, scale = 0)
	public BigDecimal getCcId() {
		return this.ccId;
	}

	public void setCcId(BigDecimal ccId) {
		this.ccId = ccId;
	}

	@Column(name = "CI_ID", precision = 22, scale = 0)
	public BigDecimal getCiId() {
		return this.ciId;
	}

	public void setCiId(BigDecimal ciId) {
		this.ciId = ciId;
	}

	@Column(name = "CWKGP_ID", precision = 22, scale = 0)
	public BigDecimal getCwkgpId() {
		return this.cwkgpId;
	}

	public void setCwkgpId(BigDecimal cwkgpId) {
		this.cwkgpId = cwkgpId;
	}

	@Column(name = "TZONE_ID", precision = 22, scale = 0)
	public BigDecimal getTzoneId() {
		return this.tzoneId;
	}

	public void setTzoneId(BigDecimal tzoneId) {
		this.tzoneId = tzoneId;
	}

	@Column(name = "CSLT_ID", precision = 22, scale = 0)
	public BigDecimal getCsltId() {
		return this.csltId;
	}

	public void setCsltId(BigDecimal csltId) {
		this.csltId = csltId;
	}

	@Column(name = "CALL_EXTERNAL_ID", nullable = false, length = 100)
	public String getCallExternalId() {
		return this.callExternalId;
	}

	public void setCallExternalId(String callExternalId) {
		this.callExternalId = callExternalId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_INITIATED_DATE", length = 7)
	public Date getCallInitiatedDate() {
		return this.callInitiatedDate;
	}

	public void setCallInitiatedDate(Date callInitiatedDate) {
		this.callInitiatedDate = callInitiatedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_CONNECTED_DATE", length = 7)
	public Date getCallConnectedDate() {
		return this.callConnectedDate;
	}

	public void setCallConnectedDate(Date callConnectedDate) {
		this.callConnectedDate = callConnectedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_AGENT_ANSWER_DATE", length = 7)
	public Date getCallAgentAnswerDate() {
		return this.callAgentAnswerDate;
	}

	public void setCallAgentAnswerDate(Date callAgentAnswerDate) {
		this.callAgentAnswerDate = callAgentAnswerDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_END_DATE", length = 7)
	public Date getCallEndDate() {
		return this.callEndDate;
	}

	public void setCallEndDate(Date callEndDate) {
		this.callEndDate = callEndDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_WORKGROUP_QUEUE_DATE", length = 7)
	public Date getCallWorkgroupQueueDate() {
		return this.callWorkgroupQueueDate;
	}

	public void setCallWorkgroupQueueDate(Date callWorkgroupQueueDate) {
		this.callWorkgroupQueueDate = callWorkgroupQueueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_DISPOSITION_DATE", length = 7)
	public Date getCallDispositionDate() {
		return this.callDispositionDate;
	}

	public void setCallDispositionDate(Date callDispositionDate) {
		this.callDispositionDate = callDispositionDate;
	}

	@Column(name = "CALL_PHONE_NUMBER", length = 20)
	public String getCallPhoneNumber() {
		return this.callPhoneNumber;
	}

	public void setCallPhoneNumber(String callPhoneNumber) {
		this.callPhoneNumber = callPhoneNumber;
	}

	@Column(name = "CALL_PHONE_TYPE", length = 1)
	public Character getCallPhoneType() {
		return this.callPhoneType;
	}

	public void setCallPhoneType(Character callPhoneType) {
		this.callPhoneType = callPhoneType;
	}

	@Column(name = "CALL_DURATION", precision = 22, scale = 0)
	public BigDecimal getCallDuration() {
		return this.callDuration;
	}

	public void setCallDuration(BigDecimal callDuration) {
		this.callDuration = callDuration;
	}

	@Column(name = "CALL_DIRECTION", nullable = false, length = 1)
	public char getCallDirection() {
		return this.callDirection;
	}

	public void setCallDirection(char callDirection) {
		this.callDirection = callDirection;
	}

	@Column(name = "CALL_TYPE_CMETA_ID", precision = 22, scale = 0)
	public BigDecimal getCallTypeCmetaId() {
		return this.callTypeCmetaId;
	}

	public void setCallTypeCmetaId(BigDecimal callTypeCmetaId) {
		this.callTypeCmetaId = callTypeCmetaId;
	}

	@Column(name = "CALL_DIALER_MODE_CMETA_ID", precision = 22, scale = 0)
	public BigDecimal getCallDialerModeCmetaId() {
		return this.callDialerModeCmetaId;
	}

	public void setCallDialerModeCmetaId(BigDecimal callDialerModeCmetaId) {
		this.callDialerModeCmetaId = callDialerModeCmetaId;
	}

	@Column(name = "CALL_ABANDONED_FLAG", nullable = false, length = 1)
	public char getCallAbandonedFlag() {
		return this.callAbandonedFlag;
	}

	public void setCallAbandonedFlag(char callAbandonedFlag) {
		this.callAbandonedFlag = callAbandonedFlag;
	}

	@Column(name = "CALL_ATTEMPTS", precision = 22, scale = 0)
	public BigDecimal getCallAttempts() {
		return this.callAttempts;
	}

	public void setCallAttempts(BigDecimal callAttempts) {
		this.callAttempts = callAttempts;
	}

	@Column(name = "CALL_CRM_ID", precision = 22, scale = 0)
	public BigDecimal getCallCrmId() {
		return this.callCrmId;
	}

	public void setCallCrmId(BigDecimal callCrmId) {
		this.callCrmId = callCrmId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_CREATE_DATE", length = 7)
	public Date getCallCreateDate() {
		return this.callCreateDate;
	}

	public void setCallCreateDate(Date callCreateDate) {
		this.callCreateDate = callCreateDate;
	}

	@Column(name = "CALL_CREATE_BY", length = 30)
	public String getCallCreateBy() {
		return this.callCreateBy;
	}

	public void setCallCreateBy(String callCreateBy) {
		this.callCreateBy = callCreateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALL_UPDATE_DATE", length = 7)
	public Date getCallUpdateDate() {
		return this.callUpdateDate;
	}

	public void setCallUpdateDate(Date callUpdateDate) {
		this.callUpdateDate = callUpdateDate;
	}

	@Column(name = "CALL_UPDATE_BY", length = 30)
	public String getCallUpdateBy() {
		return this.callUpdateBy;
	}

	public void setCallUpdateBy(String callUpdateBy) {
		this.callUpdateBy = callUpdateBy;
	}

	@Column(name = "CALL_SECONDARY_EXT_ID", length = 100)
	public String getCallSecondaryExtId() {
		return this.callSecondaryExtId;
	}

	public void setCallSecondaryExtId(String callSecondaryExtId) {
		this.callSecondaryExtId = callSecondaryExtId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "call")
	public Set getCallEvents() {
		return this.callEvents;
	}

	public void setCallEvents(Set callEvents) {
		this.callEvents = callEvents;
	}

}
