package com.dd.mdr.model.f;
// Generated Mar 11, 2016 5:28:44 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "LOCATION", schema = "DDMDR")
public class Location implements java.io.Serializable {

	private BigDecimal locId;
	private String locExternalId;
	private String locName;
	private Date locCreateDate;
	private String locCreateBy;
	private Date locUpdateDate;
	private String locUpdateBy;
	private Set calls = new HashSet(0);

	public Location() {
	}

	public Location(BigDecimal locId, String locExternalId, String locName) {
		this.locId = locId;
		this.locExternalId = locExternalId;
		this.locName = locName;
	}

	public Location(BigDecimal locId, String locExternalId, String locName, Date locCreateDate, String locCreateBy,
			Date locUpdateDate, String locUpdateBy, Set calls) {
		this.locId = locId;
		this.locExternalId = locExternalId;
		this.locName = locName;
		this.locCreateDate = locCreateDate;
		this.locCreateBy = locCreateBy;
		this.locUpdateDate = locUpdateDate;
		this.locUpdateBy = locUpdateBy;
		this.calls = calls;
	}

	@Id

	@Column(name = "LOC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLocId() {
		return this.locId;
	}

	public void setLocId(BigDecimal locId) {
		this.locId = locId;
	}

	@Column(name = "LOC_EXTERNAL_ID", nullable = false, length = 20)
	public String getLocExternalId() {
		return this.locExternalId;
	}

	public void setLocExternalId(String locExternalId) {
		this.locExternalId = locExternalId;
	}

	@Column(name = "LOC_NAME", nullable = false)
	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOC_CREATE_DATE", length = 7)
	public Date getLocCreateDate() {
		return this.locCreateDate;
	}

	public void setLocCreateDate(Date locCreateDate) {
		this.locCreateDate = locCreateDate;
	}

	@Column(name = "LOC_CREATE_BY", length = 30)
	public String getLocCreateBy() {
		return this.locCreateBy;
	}

	public void setLocCreateBy(String locCreateBy) {
		this.locCreateBy = locCreateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOC_UPDATE_DATE", length = 7)
	public Date getLocUpdateDate() {
		return this.locUpdateDate;
	}

	public void setLocUpdateDate(Date locUpdateDate) {
		this.locUpdateDate = locUpdateDate;
	}

	@Column(name = "LOC_UPDATE_BY", length = 30)
	public String getLocUpdateBy() {
		return this.locUpdateBy;
	}

	public void setLocUpdateBy(String locUpdateBy) {
		this.locUpdateBy = locUpdateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set getCalls() {
		return this.calls;
	}

	public void setCalls(Set calls) {
		this.calls = calls;
	}

}
