package com.dd.mdr.model.f;
// Generated Mar 11, 2016 5:28:44 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SourceLog generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_LOG", schema = "DDMDR", uniqueConstraints = @UniqueConstraint(columnNames = { "SJ_ID",
		"SL_OBJECT_NAME" }) )
public class SourceLog implements java.io.Serializable {

	private BigDecimal slId;
	private BigDecimal sjId;
	private String slObjectName;
	private BigDecimal slRecordCount;
	private BigDecimal slRejectCount;
	private String scCode;
	private String slResult;
	private Clob slErrorLog;
	private Date slCreateDate;
	private String slCreateBy;
	private Date slUpdateDate;
	private String slUpdateBy;
	private Set calls = new HashSet(0);

	public SourceLog() {
	}

	public SourceLog(BigDecimal slId, BigDecimal sjId, String slObjectName, BigDecimal slRecordCount, String scCode) {
		this.slId = slId;
		this.sjId = sjId;
		this.slObjectName = slObjectName;
		this.slRecordCount = slRecordCount;
		this.scCode = scCode;
	}

	public SourceLog(BigDecimal slId, BigDecimal sjId, String slObjectName, BigDecimal slRecordCount,
			BigDecimal slRejectCount, String scCode, String slResult, Clob slErrorLog, Date slCreateDate,
			String slCreateBy, Date slUpdateDate, String slUpdateBy, Set calls) {
		this.slId = slId;
		this.sjId = sjId;
		this.slObjectName = slObjectName;
		this.slRecordCount = slRecordCount;
		this.slRejectCount = slRejectCount;
		this.scCode = scCode;
		this.slResult = slResult;
		this.slErrorLog = slErrorLog;
		this.slCreateDate = slCreateDate;
		this.slCreateBy = slCreateBy;
		this.slUpdateDate = slUpdateDate;
		this.slUpdateBy = slUpdateBy;
		this.calls = calls;
	}

	@Id

	@Column(name = "SL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSlId() {
		return this.slId;
	}

	public void setSlId(BigDecimal slId) {
		this.slId = slId;
	}

	@Column(name = "SJ_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSjId() {
		return this.sjId;
	}

	public void setSjId(BigDecimal sjId) {
		this.sjId = sjId;
	}

	@Column(name = "SL_OBJECT_NAME", nullable = false, length = 100)
	public String getSlObjectName() {
		return this.slObjectName;
	}

	public void setSlObjectName(String slObjectName) {
		this.slObjectName = slObjectName;
	}

	@Column(name = "SL_RECORD_COUNT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSlRecordCount() {
		return this.slRecordCount;
	}

	public void setSlRecordCount(BigDecimal slRecordCount) {
		this.slRecordCount = slRecordCount;
	}

	@Column(name = "SL_REJECT_COUNT", precision = 22, scale = 0)
	public BigDecimal getSlRejectCount() {
		return this.slRejectCount;
	}

	public void setSlRejectCount(BigDecimal slRejectCount) {
		this.slRejectCount = slRejectCount;
	}

	@Column(name = "SC_CODE", nullable = false, length = 30)
	public String getScCode() {
		return this.scCode;
	}

	public void setScCode(String scCode) {
		this.scCode = scCode;
	}

	@Column(name = "SL_RESULT", length = 15)
	public String getSlResult() {
		return this.slResult;
	}

	public void setSlResult(String slResult) {
		this.slResult = slResult;
	}

	@Column(name = "SL_ERROR_LOG")
	public Clob getSlErrorLog() {
		return this.slErrorLog;
	}

	public void setSlErrorLog(Clob slErrorLog) {
		this.slErrorLog = slErrorLog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SL_CREATE_DATE", length = 7)
	public Date getSlCreateDate() {
		return this.slCreateDate;
	}

	public void setSlCreateDate(Date slCreateDate) {
		this.slCreateDate = slCreateDate;
	}

	@Column(name = "SL_CREATE_BY", length = 30)
	public String getSlCreateBy() {
		return this.slCreateBy;
	}

	public void setSlCreateBy(String slCreateBy) {
		this.slCreateBy = slCreateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SL_UPDATE_DATE", length = 7)
	public Date getSlUpdateDate() {
		return this.slUpdateDate;
	}

	public void setSlUpdateDate(Date slUpdateDate) {
		this.slUpdateDate = slUpdateDate;
	}

	@Column(name = "SL_UPDATE_BY", length = 30)
	public String getSlUpdateBy() {
		return this.slUpdateBy;
	}

	public void setSlUpdateBy(String slUpdateBy) {
		this.slUpdateBy = slUpdateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourceLog")
	public Set getCalls() {
		return this.calls;
	}

	public void setCalls(Set calls) {
		this.calls = calls;
	}

}
